Instead of std::process::exit, raise Err from main
This is not ideal, as the error message is now:

Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

but it's pretty clean.